### ISSUE TITLE
Reloading glue from the REPL?

### ISSUE THREAD

**Issue by WhittlesJr** [lambdaisland/kaocha-cucumber#12]
I've been trying to work with cucumber from the REPL, using `kaocha.repl/run`. I find that merely reloading the glue namespaces is not enough to refresh the glue code from `cucumber-jvm-clojure`'s perspective. 

What would a REPL-based workflow look like for working on and reloading glue code? Running from the CLI is not a great option for development for us, because our code takes a long time to init.

**Comment by WhittlesJr** [comment]
It looks like all you need to do is `(reset! lambdaisland.cucumber.jvm/glue-cache nil)`.

I'm not sure if this implies that there should be any changes to your code or not, but for anyone else who finds this issue, this is what you have to do after refreshing your code.

**Comment by humorless** [comment]
solve with https://github.com/lambdaisland/kaocha-cucumber/pull/16
