### ISSUE TITLE
Filtering by tag?

### ISSUE THREAD

**Issue by WhittlesJr** [lambdaisland/kaocha-cucumber#13]
Given that you support `@` tags in feature files, is there currently a way to filter which tests Kaocha runs using those tags?

**Comment by plexus** [comment]
I think we might put them on the test metadata? not sure. Check `bin/kaocha --print-test-plan`, see if they show up in there.

**Comment by alysbrooks** [comment]
I tried it in Kaocha, and it does add these Cucumber tags to meta.

**Comment by alysbrooks** [comment]
Started on #14 to document it.

**Comment by alysbrooks** [comment]
This was completed in October, closing.
