### ISSUE TITLE
Way to have "default steps"?

### ISSUE THREAD

**Issue by zilti** [lambdaisland/kaocha-cucumber#5]
We're considering using kaocha-cucumber for browser testing of our project. Since that means there are, no matter which feature, a lot of similar steps, I wonder if there is a way to define "default" steps that will be used when none is defined in the specific namespace. Like e.g. `"If I click on the element with id {string}"` is something we would use in many feature files, and this would otherwise mean to have duplicate code.

**Comment by plexus** [comment]
Would `(Before ...)` hooks or `Background:` blocks do the trick?

- https://github.com/lambdaisland/kaocha-cucumber/blob/master/src/lambdaisland/cucumber/dsl.clj#L115-L116
- https://cucumber.io/docs/gherkin/reference/#background

**Comment by zilti** [comment]
Not really, no... Maybe I am thinking too low-level? But a step like "And I click on the element with id {string}" can be used across many features, which it seems would mean that I have to define it anew in every feature using it.

Backgrounds also are restricted to one feature each, and a `Before` block is executed at the beginning of every scenario of a feature, if I understood that correctly.

**Comment by plexus** [comment]
Then I'm afraid I can't help you

**Comment by zilti** [comment]
Thanks nonetheless! And we are actually using kaocha-cucumber for our software now.
