### ISSUE TITLE
Support for the Rule keyword in Gherkin 6 

### ISSUE THREAD

**Issue by kgxsz** [lambdaisland/kaocha-cucumber#7]
Hi 👋  
This lib has been really useful for us these past months.
We've recently wanted to use the `Rule` keyword that seems to be supported by Gherkin 6.
Is this something that might be happening in future?

Thanks.

**Comment by plexus** [comment]
If you're asking if I would merge a PR for that then yes, I'd be happy to include that.

kaocha-cucumber is not in active development at the moment so unless a contributor steps up this is unlikely to happen spontaneously, but we are available for commercial support, including making sure our libraries suit the needs of our clients. Feel free to contact me if you like to have a chat about what the options are.

**Comment by alysbrooks** [comment]
This is not going to be a high priority for the team, but we are welcome to PRs (and you can always reach out about commercial support as Arne mentioned).
